- name: Enable apache2 service
  systemd:
    name: apache2
    enabled: yes
  become: true                    

- name: Sync files from github directory to web
  ansible.builtin.synchronize:
    src: "{{ git_dir }}/html/"
    dest: "{{ web_dir }}/"
    delete: false
    recursive: true
  become: yes

- name: Sync images
  ansible.builtin.shell:
    cmd: rsync -av --exclude='.*' {{ nfs_target }}/images/ /{{ web_dir }}/images/
  become: yes

- name: Sync cache
  ansible.builtin.shell:
    cmd: rsync -av --exclude='.*' {{ nfs_target }}/cache/ /{{ web_dir }}/resources/cache/
  become: yes

- name: Sync gallery-images      
  ansible.builtin.shell:
    cmd: rsync -av --exclude='.*' {{ nfs_target }}/gallery-images/ /{{ web_dir }}/gallery-images/
  become: yes

- name: Set permissions for /var/www/html
  ansible.builtin.file:
    path: "{{ web_dir }}"
    mode: "0775"
    recurse: yes
  become: yes

- name: Set permissions for cache
  ansible.builtin.file:
    path: "{{ web_dir }}/resources/cache"
    mode: "0777"        
    recurse: yes        
  become: yes

- name: Delete /var/www/html/index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent
  become: yes






