packer {
  required_plugins {
    proxmox = {
      version = ">= 1.1.2"
      source  = "github.com/hashicorp/proxmox"
    }
    ansible = {
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }
  }
}

locals {
  my_public_key = trimspace(file("~/.ssh/id_rsa.pub"))
}

variable "ssh_password" {
  type      = string
  sensitive = true
  default   = null 
}


variable "proxmox_vmid" {
  type        = string
  description = "The specific VMID from wedding inventory. Generated by script"
}

variable "proxmox_api_token_secret" {
  type      = string
  sensitive = true
}

variable "target_app" {
  type    = string
  # No default, must be an argument
}

variable "proxmox_api_url" { type = string }

source "proxmox-iso" "wedding-base" {
  proxmox_url = var.proxmox_api_url
  vm_id       = var.proxmox_vmid
  username    = "terraform@pam!main_terraform"
  token       = var.proxmox_api_token_secret

  node    = "pve"
  vm_name = "wedding-golden"
  pool     = "Template"


  # Use the modern boot_iso block
  boot_iso {
    type         = "scsi"
    iso_file     = "truenas-nfs:iso/debian-13.3.0-amd64-netinst.iso"
    unmount      = true
  }

  # Simple disk definition - use type 'scsi' and ensure scsi_controller is set
  scsi_controller = "virtio-scsi-pci"
  disks {
    disk_size    = "6G"
    format       = "raw"
    storage_pool = "local-zfs"
    type         = "scsi"
  }

  cores  = 4
  memory = 4096

  network_adapters {
    model    = "virtio"
    bridge   = "vmbr0"
    firewall = false
  }

  http_bind_address = "192.168.11.17"
  http_port_min     = 8795
  http_port_max     = 8795

  http_content = {
    "/preseed.cfg" = templatefile("preseed.pkrtpl.hcl", { ssh_key = local.my_public_key })
  }

  boot_wait = "10s" 
  
  boot_command = [
    "<esc><wait>",
    "install <wait>",
    "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg <wait>",
    "debian-installer/locale=en_US.UTF-8 <wait>",
    "keyboard-configuration/xkb-keymap=us <wait>",
    "netcfg/get_hostname=proxy <wait>",
    "netcfg/get_domain=unassigned-domain <wait>",
    "fb=false debconf/priority=critical <wait>",
    "DEBIAN_FRONTEND=noninteractive <wait>", # Forces the installer to never ask questions
    "auto=true <wait>",
    "interface=auto <wait>",
    "<enter><wait10>",
    "<leftAltOn><f4><leftAltOff>"
  ]

  ssh_username = "kevin"
  ssh_handshake_attempts = 100
  ssh_timeout  = "15m"
  ssh_private_key_file = "~/.ssh/id_rsa"
}

build {
  sources = ["proxmox-iso.wedding-base"]

  # Step 1: Run your existing Ansible roles
  provisioner "ansible" {
    playbook_file = "./_packer-build.yaml"
    user          = "kevin"
    use_proxy     = false
    ansible_env_vars = [
      "ANSIBLE_ROLES_PATH=./roles",
      "ANSIBLE_HOST_KEY_CHECKING=False"
    ]
    # Pass target_app variable
    extra_arguments = [
      "--extra-vars", "target_app=${var.target_app}"
    ]
  }

  # Step 2: Final Sanitization 
  provisioner "shell" {
    inline = [
      "sudo cloud-init clean --logs", # Crucial: Tells the OS "You haven't booted yet"
      "sudo rm -f /etc/netplan/00-installer-config.yaml", # Remove Packer's network config
      "sudo truncate -s 0 /etc/machine-id",
      "sudo sync",
      "sudo rm /etc/environment"
    ]
  }
  post-processor "shell-local" {
    inline = [
      # copy the disk from local-zfs to NAS (nfs)
    "ssh root@pve 'qm move_disk ${var.proxmox_vmid} scsi0 truenas-nfs --delete'"    ]
  }
}